// 初始化菜单数据
let data = [{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1,
    "menuName": "系统管理",
    "parentName": null,
    "parentId": 0,
    "orderNum": 1,
    "path": "system",
    "component": null,
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "M",
    "visible": "0",
    "status": "0",
    "perms": "",
    "icon": "system",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 2,
    "menuName": "系统监控",
    "parentName": null,
    "parentId": 0,
    "orderNum": 2,
    "path": "monitor",
    "component": null,
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "M",
    "visible": "0",
    "status": "0",
    "perms": "",
    "icon": "monitor",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 100,
    "menuName": "用户管理",
    "parentName": null,
    "parentId": 1,
    "orderNum": 1,
    "path": "user",
    "component": "system/user/index",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "C",
    "visible": "0",
    "status": "0",
    "perms": "system:user:list",
    "icon": "user",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 101,
    "menuName": "角色管理",
    "parentName": null,
    "parentId": 1,
    "orderNum": 2,
    "path": "role",
    "component": "system/role/index",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "C",
    "visible": "0",
    "status": "0",
    "perms": "system:role:list",
    "icon": "peoples",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 102,
    "menuName": "菜单管理",
    "parentName": null,
    "parentId": 1,
    "orderNum": 3,
    "path": "menu",
    "component": "system/menu/index",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "C",
    "visible": "0",
    "status": "0",
    "perms": "system:menu:list",
    "icon": "tree-table",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 103,
    "menuName": "部门管理",
    "parentName": null,
    "parentId": 1,
    "orderNum": 4,
    "path": "dept",
    "component": "system/dept/index",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "C",
    "visible": "0",
    "status": "0",
    "perms": "system:dept:list",
    "icon": "tree",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 104,
    "menuName": "岗位管理",
    "parentName": null,
    "parentId": 1,
    "orderNum": 5,
    "path": "post",
    "component": "system/post/index",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "C",
    "visible": "0",
    "status": "0",
    "perms": "system:post:list",
    "icon": "post",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 105,
    "menuName": "字典管理",
    "parentName": null,
    "parentId": 1,
    "orderNum": 6,
    "path": "dict",
    "component": "system/dict/index",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "C",
    "visible": "0",
    "status": "0",
    "perms": "system:dict:list",
    "icon": "dict",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1001,
    "menuName": "用户查询",
    "parentName": null,
    "parentId": 100,
    "orderNum": 1,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:user:query",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1002,
    "menuName": "用户新增",
    "parentName": null,
    "parentId": 100,
    "orderNum": 2,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:user:add",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1003,
    "menuName": "用户修改",
    "parentName": null,
    "parentId": 100,
    "orderNum": 3,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:user:edit",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1004,
    "menuName": "用户删除",
    "parentName": null,
    "parentId": 100,
    "orderNum": 4,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:user:remove",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1005,
    "menuName": "用户导出",
    "parentName": null,
    "parentId": 100,
    "orderNum": 5,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:user:export",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1006,
    "menuName": "用户导入",
    "parentName": null,
    "parentId": 100,
    "orderNum": 6,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:user:import",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1007,
    "menuName": "重置密码",
    "parentName": null,
    "parentId": 100,
    "orderNum": 7,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:user:resetPwd",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1008,
    "menuName": "角色查询",
    "parentName": null,
    "parentId": 101,
    "orderNum": 1,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:role:query",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1009,
    "menuName": "角色新增",
    "parentName": null,
    "parentId": 101,
    "orderNum": 2,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:role:add",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1010,
    "menuName": "角色修改",
    "parentName": null,
    "parentId": 101,
    "orderNum": 3,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:role:edit",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1011,
    "menuName": "角色删除",
    "parentName": null,
    "parentId": 101,
    "orderNum": 4,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:role:remove",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1012,
    "menuName": "角色导出",
    "parentName": null,
    "parentId": 101,
    "orderNum": 5,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:role:export",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1013,
    "menuName": "菜单查询",
    "parentName": null,
    "parentId": 102,
    "orderNum": 1,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:menu:query",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1014,
    "menuName": "菜单新增",
    "parentName": null,
    "parentId": 102,
    "orderNum": 2,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:menu:add",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1015,
    "menuName": "菜单修改",
    "parentName": null,
    "parentId": 102,
    "orderNum": 3,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:menu:edit",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1016,
    "menuName": "菜单删除",
    "parentName": null,
    "parentId": 102,
    "orderNum": 4,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:menu:remove",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1017,
    "menuName": "部门查询",
    "parentName": null,
    "parentId": 103,
    "orderNum": 1,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:dept:query",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1018,
    "menuName": "部门新增",
    "parentName": null,
    "parentId": 103,
    "orderNum": 2,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:dept:add",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1019,
    "menuName": "部门修改",
    "parentName": null,
    "parentId": 103,
    "orderNum": 3,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:dept:edit",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1020,
    "menuName": "部门删除",
    "parentName": null,
    "parentId": 103,
    "orderNum": 4,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:dept:remove",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1021,
    "menuName": "岗位查询",
    "parentName": null,
    "parentId": 104,
    "orderNum": 1,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:post:query",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1022,
    "menuName": "岗位新增",
    "parentName": null,
    "parentId": 104,
    "orderNum": 2,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:post:add",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1023,
    "menuName": "岗位修改",
    "parentName": null,
    "parentId": 104,
    "orderNum": 3,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:post:edit",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1024,
    "menuName": "岗位删除",
    "parentName": null,
    "parentId": 104,
    "orderNum": 4,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:post:remove",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1025,
    "menuName": "岗位导出",
    "parentName": null,
    "parentId": 104,
    "orderNum": 5,
    "path": "",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:post:export",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1026,
    "menuName": "字典查询",
    "parentName": null,
    "parentId": 105,
    "orderNum": 1,
    "path": "#",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:dict:query",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1027,
    "menuName": "字典新增",
    "parentName": null,
    "parentId": 105,
    "orderNum": 2,
    "path": "#",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:dict:add",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1028,
    "menuName": "字典修改",
    "parentName": null,
    "parentId": 105,
    "orderNum": 3,
    "path": "#",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:dict:edit",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1029,
    "menuName": "字典删除",
    "parentName": null,
    "parentId": 105,
    "orderNum": 4,
    "path": "#",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:dict:remove",
    "icon": "#",
     "children": []
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": null,
    "menuId": 1030,
    "menuName": "字典导出",
    "parentName": null,
    "parentId": 105,
    "orderNum": 5,
    "path": "#",
    "component": "",
    "query": "",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:dict:export",
    "icon": "#",
     "children": []
    
  },{
    
    "menuId": "t924jUUD",
    "menuName": "充值续费",
    "parentId": 100,
    "orderNum": 2,
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system.user.setGold",
    "icon": "button",
     "children": []
    
  },{
    
    "menuId": "wuWvzD4N",
    "menuName": "登录日志",
    "parentId": "2",
    "orderNum": 1,
    "path": "login",
    "component": "monitor/logininfor/index",
    "isFrame": "1",
    "isCache": "0",
    "menuType": "C",
    "visible": "0",
    "status": "0",
    "perms": "monitor:logininfor:index",
    "icon": "cascader",
     "children": []
    
  },{
    
    "menuId": "DS8gwVSW",
    "menuName": "删除",
    "parentId": "wuWvzD4N",
    "orderNum": 2,
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "system:logininfor:remove",
    "icon": "button",
     "children": []
    
  },{
    
    "menuId": "AHw47WPC",
    "menuName": "查询",
    "parentId": "wuWvzD4N",
    "orderNum": 1,
    "isFrame": "1",
    "isCache": "0",
    "menuType": "F",
    "visible": "0",
    "status": "0",
    "perms": "monitor:logerininfor:query",
    "icon": "system",
     "children": []
    
  },{
    "menuId":"CkEm3RtA",
    "menuName":"内容管理",
    "parentId":"0",
    "orderNum":6,
    "path":"product",
    "isFrame":"1",
    "isCache":"0",
    "menuType":"M",
    "visible":"0",
    "status":"0",
    "icon":"chart",
    "children":[

    ]
},{
  "menuId":"KoAkDjeR",
  "menuName":"数据库管理",
  "parentId":"CkEm3RtA",
  "orderNum":3,
  "path":"mongodata",
  "component":"mongoData/index",
  "isFrame":"1",
  "isCache":"0",
  "menuType":"C",
  "visible":"0",
  "status":"0",
  "icon":"job",
  "children":[

  ]
},{
    
  "menuId": "IKI52Bv5",
  "menuName": "guiplan官网",
  "parentId": 0,
  "orderNum": 2,
  "path": "http://www.guiplan.com",
  "isFrame": "0",
  "isCache": "0",
  "menuType": "M",
  "visible": "0",
  "status": "0",
  "icon": "cascader",
   "children": []
  
}]
module.exports =  data