let data = [{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": "超级管理员",
    "roleId": 1,
    "roleName": "超级管理员",
    "roleKey": "admin",
    "roleSort": "1",
    "dataScope": "1",
    "menuCheckStrictly": true,
    "deptCheckStrictly": true,
    "status": "0",
    "delFlag": "0",
    "flag": false,
    "menuIds": null,
    "deptIds": null,
    "admin": true
    
  },{
    
    "searchValue": null,
    "createBy": null,
    "updateBy": null,
    "remark": "普通角色",
    "roleId": 2,
    "roleName": "普通角色",
    "roleKey": "common",
    "roleSort": 3,
    "dataScope": "2",
    "menuCheckStrictly": true,
    "deptCheckStrictly": true,
    "status": "0",
    "delFlag": "0",
    "flag": false,
    "menuIds": [
      "eU3cDa1ZL",
      "85padPUehu",
      "SudqNBaSUA",
      "vo4edU6JtQ",
      "gMiMFDy9n",
      "urh0eUDxFk_",
      "GX3BGkVLpwW",
      "1CJmF4GZA"
    ],
    "deptIds": null
  },{
    
    "roleName": "游客",
    "roleKey": "youke",
    "roleSort": 4,
    "menuCheckStrictly": true,
    "deptCheckStrictly": true,
    "status": "0",
    "menuIds": [
      "eU3cDa1ZL",
      "85padPUehu",
      "urh0eUDxFk_",
      "ex8MXdXnwjt",
      "dnxcJ1JyoSX",
      "w1elMSwbnN3",
      "rh38vIzkd3g",
      "0J1sEjmkHCt",
      "8QGd3qTzqA7",
      "JG1taZ272f",
      "Rh4Jxwbfv3g",
      "K-N4Tvh2H6d",
      "Xuxd_qNncfH",
      "-ypMHQgxuH5",
      "YwDF_SMc2C4",
      "pHQwbvfBoQ",
      "vPouNVbrYCA",
      "5pSaZdcAgRK",
      "igU5XSZYRUu",
      "G2Q0ejEzfhs",
      "SudqNBaSUA",
      "GX3BGkVLpwW",
      "5KMvdzf-1ge",
      "X7zZjMNRTaH",
      "TQ23AepInrT",
      "6hUpyl2cDS",
      "bfADebYu-Xi",
      "crxbmJfvU69",
      "89qQXVnvuGu",
      "c1LPbAYX8nB",
      "2Zpd5ySlODz",
      "6oOe2GjWnE",
      "rPR0IeN6cxV",
      "cQeglbWQAHG",
      "OkG35QukGlt",
      "wtkFyhtPnJb",
      "WylQbBviPXR",
      "W7cGLQfyUj",
      "P24bAiJs-up",
      "mXij6E5uQR0",
      "-rEZKWS8GNa",
      "KAi_YWtF-cv",
      "GoABxES6rD6",
      "Ffrd5erXLZ",
      "5ouc9zyhQqw",
      "NbYgnc6CNhH",
      "U7zqWBgpYTq",
      "TCXa2VYYd92",
      "8PIjGP6l5X",
      "65nDT_30JiI",
      "VxMfPqgkYk",
      "vE_2hSW7b2",
      "NARBO6arEi",
      "aU57xkyX5X1",
      "vCb_1XQiXRy",
      "x0NqET3Hmbl",
      "mYg0lG4dxr0",
      "71fySeyaih",
      "Lr7xfaVff6l",
      "w9xhIEzcf5M",
      "2p-HfUhBXo",
      "ZY_443B8Vq",
      "62Wx19mSPS",
      "znqlAcdDMy",
      "1ftlSh3htS",
      "PVJKEOy4Fx",
      "dU-0RS2B7OV"
    ],
    "deptIds": [],
    "flag": false,
    
  },{
    
    "remark": "黑名单不允许登录",
    "roleName": "黑名单",
    "roleKey": "blacklist",
    "roleSort": 0,
    "menuCheckStrictly": true,
    "deptCheckStrictly": true,
    "status": "0",
    "menuIds": [],
    "deptIds": [],
    "flag": false,
    
  }]
module.exports = data